### ISSUE TITLE
To many open files

### ISSUE THREAD

**Issue by mstruebing** [mstruebing/tldr#22]
```
2017/10/20 09:23:57 ERROR: creating cache repository: ERROR: loading data from remote: ERROR: unzipping pages: err opening file '/Users/simon/.tldr/pages/common/mysql.md': open /Users/simon/.tldr/pages/common/mysql.md: too many open files
```

quick research: https://github.com/golang/go/issues/3978

https://github.com/mstruebing/tldr/blob/master/cache/cache.go#L197

**Comment by gavinwade12** [comment]
I thought this might become an issue. I really don't like having so many defer statements in a loop. I'll take a look at this today.
