### ISSUE TITLE
Foreground color not restored after rendering a page

### ISSUE THREAD

**Issue by kostix** [mstruebing/tldr#23]
Experiencing at ed5714260dde7dc71ea78e055952603c7c79b710 on Debian Stretch amd64 while running `tldr` from `rxvt-unicode` v 9.22 in 256 colors mode, that is, I have

```
~$ echo $TERM
rxvt-unicode-256color
```

The bug manifests itself in that the `PS1` shell's prompt goes rendered in black color after `tldr stack` is run. Running `reset` gets the foreground color back to normal.

Two bits of information which might help:

- I use `bash` with no-frills `PS1`, that is, my `PS1` does not use any ANSI color sequences in it.
- I have `rxvt` background set to ` #3f3f3f` and foreground to `#dcdccc` (IOW my background it not exactly black).

**Comment by mstruebing** [comment]
Thank you for reporting these bug.
I think this is because of this: https://github.com/mstruebing/tldr/blob/master/render.go#L10-L14
Which are ansi escape sequences if I remember correctly.

**Comment by kostix** [comment]
I'd add, from looking at [this](https://github.com/mstruebing/tldr/blob/master/render.go#L14) that on my system, executing `echo -ne '\033[0m'` — as suggested [here](https://stackoverflow.com/a/33206814/720999) — resets the terminal colors just like `reset` does.

**Comment by kostix** [comment]
Works for me, thanks.
