### ISSUE TITLE
Make autocompletion autoinstallable

### ISSUE THREAD

**Issue by mstruebing** [mstruebing/tldr#34]
I'm not sure if this is a good idea becuase that means to manipulate the users `.zshrc` or `.bashrc`.

If you have suggestions please let me know.

**Comment by agnivade** [comment]
It should be autoinstalled. But no need to manipulate `.bashrc`. You can directly place the file under `/etc/bash_completion.d/`. Its the same way tools like docker, git do auto completion. 

But you have to figure out for macOS though. Should be the same, but I am not sure.

**Comment by mstruebing** [comment]
It should be already there: https://github.com/mstruebing/tldr/blob/master/Makefile#L16
