### ISSUE TITLE
If XDG_CACHE_HOME is not defined, I believe it will try to delete /tldr from root folder

### ISSUE THREAD

**Issue by danielwangksu** [mstruebing/tldr#51]
It might not hurt anything, but no a good idea to do and it is not the code intention

https://github.com/mstruebing/tldr/blob/afe0c461cbfe10ab62bbf4b3feebf3367563b0b7/Makefile#L65

**Comment by mstruebing** [comment]
Hey @danielwangksu thank you for your issue :rocket: 

I can see your concern, but as this only will be executed by developers of that software it is not so harmful as that's no user facing code. However, I understand that this can happen, if you want, you can provide a PR for it.
